---
package: chroma_decoder

main: chroma_decoder/main.py

# boot:

# libs:
#   - file.py

requirements:
  # https://github.com/miketeachman/micropython-rotary
  - github:miketeachman/micropython-rotary
